### ISSUE TITLE
Update playbook

### ISSUE THREAD

**Issue by lukefretwell** [CityCamp/citycamp.github.io#27]
## Reference
 
- http://citycamp.com/playbook/
- https://docs.google.com/document/d/1nvZp2fcV7bS8S-HFZEJxuJyqAmRVNXaqf5Rt2RGuSQQ/edit?usp=sharing

## To-do

- [x] Review comments
- [x] Break out sections into tabs
- [x] Create issues for each tab
- [x] Call for support for each issue
- [x] Add letter to Chamber of commerce (to request space + sponsorship)
